import {} from "./types";

/***
 * This file is a custom type definition for the Sanity schema.
 * It is used to define the types of the custom content fields in the Sanity schema.
 * The types defined here are used in the frontend to render the custom content fields.
 * Update custom types accordingly after running sanity typegen. The custom types are not generated by the typegen command.
 * Will only need to be updated if the schema changes for the extended types here.
 * The custom types are named with the prefix "Custom_" or "Custom" to avoid conflicts with the generated types and easier lookup.
 * Import the custom types through sanity/types in the frontend.
 */

declare module "sanity/types" {
  export type CustomContent = Omit<
    NonNullable<Content>,
    "video" & {
      video: CustomVideo;
    }
  >;

  export type Custom_ARTICLE_QUERYResult = Omit<
    NonNullable<ARTICLE_QUERYResult>,
    "video" | "text"
  > & {
    video: CustomVideo;
    text: CustomContent;
  };
}

type CustomVideo = {
  title: string;
  muxVideo: {
    asset: {
      playbackId: string;
    };
  };
};
